### ISSUE TITLE
Web File Explorer not working, missing BIN file?

### ISSUE THREAD

**Issue by Antaniserse** [goweiwen/Allium#53]
Web File Explorer seems to be not working

Wi-Fi is on, FTP access is working fine, but turning on Web File Explorer does nothing... looking at the **dufs-on.sh** script, it does seems there are files missing in the /.allium/bin/ folder

**Comment by goweiwen** [comment]
Oops... I'll drop a new release to fix this, thanks!

**Comment by Antaniserse** [comment]
0.24.2 working perfectly now

**Comment by lemonlimelabs** [comment]
I've been trying to get this feature to work. I don't know what I'm doing incorrect, but I cannot get the file browser in a web browser to work. I can FTP through windows explorer, but in an internet browser I cannot connect to the Miyoo's IP address. I know my computer is on the same network and I know I'm using the correct IP address, because I can get the FTP through explorer to work. I though the web file explorer would be different than the FTP in explorer, am I mistaken? on the WIFI setup screen I've tried a bunch of combinations of NTP, Web File, Explorer, Telnet, and FTP enabling but no cigar. Any way I could help troubleshoot this to see if there is a bug still? Using Google Chrome as the web browser. Thank you.

**Comment by lemonlimelabs** [comment]
Okay, I fresh install solved it, apologies. I tried an update and for whatever reason it didn't work. For anybody having this issue try a fresh install.

**Comment by goweiwen** [comment]
Glad you figured it out yourself.

The web file browser is located in the .tmp_update folder, so you have to copy that over when updating.

**Comment by tomh79** [comment]
what is the FTP login?

**Comment by tomh79** [comment]
I tried to get FTP and WebExplorer to work. No luck. Wifi connected, have an IP adress - no connection with FTP or Web File Explorer. Fresh install did not solve the problem. Any more hints how to solve this?
